"""add_contact_emails_to_clients

Revision ID: 00e2fa5ba41f
Revises: 0392542b7676
Create Date: 2026-02-26 11:05:42.742347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00e2fa5ba41f'
down_revision: Union[str, Sequence[str], None] = '0392542b7676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients_v2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('contact2_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('contact3_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('contact4_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['treasury_transaction_id'])
        batch_op.create_foreign_key(None, 'bank_accounts', ['approved_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'bank_transactions', ['treasury_transaction_id'], ['id'])
        batch_op.create_foreign_key(None, 'bank_accounts', ['suggested_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('clients_v2', schema=None) as batch_op:
        batch_op.drop_column('contact4_email')
        batch_op.drop_column('contact3_email')
        batch_op.drop_column('contact2_email')
        batch_op.drop_column('contact_email')

    # ### end Alembic commands ###
