"""add_treasury_links_to_payments

Revision ID: 0392542b7676
Revises: 83777882d85f
Create Date: 2026-02-21 10:46:28.225044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0392542b7676'
down_revision: Union[str, Sequence[str], None] = '83777882d85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sp_treasury_tx_id', ['treasury_transaction_id'])
        batch_op.create_foreign_key('fk_sp_approved_account', 'bank_accounts', ['approved_account_id'], ['id'])
        batch_op.create_foreign_key('fk_sp_suggested_account', 'bank_accounts', ['suggested_account_id'], ['id'])
        batch_op.create_foreign_key('fk_sp_treasury_tx', 'bank_transactions', ['treasury_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sp_treasury_tx', type_='foreignkey')
        batch_op.drop_constraint('fk_sp_suggested_account', type_='foreignkey')
        batch_op.drop_constraint('fk_sp_approved_account', type_='foreignkey')
        batch_op.drop_constraint('uq_sp_treasury_tx_id', type_='unique')

    # ### end Alembic commands ###