"""add_provider_and_cost_to_requisitions

Revision ID: 2f8c65712333
Revises: 686bdc1e0774
Create Date: 2026-04-27 10:46:04.294167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f8c65712333'
down_revision: Union[str, Sequence[str], None] = '686bdc1e0774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expected_unit_cost', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_req_provider_id', 'providers', ['provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_req_provider_id', type_='foreignkey')
        batch_op.drop_column('expected_unit_cost')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
