"""schema_final_clean

Revision ID: 38ab24f34ea2
Revises: 
Create Date: 2026-02-01 12:54:27.079614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38ab24f34ea2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfc_tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact2_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact2_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact2_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact3_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact3_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact3_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact4_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact4_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact4_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_v2_full_name'), 'clients_v2', ['full_name'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rfc_tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_business_name'), 'providers', ['business_name'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('DIRECTOR', 'ADMIN', 'SALES', 'DESIGN', 'WAREHOUSE', 'PRODUCTION', name='userrole'), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('design_product_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('blueprint_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_product_masters_name'), 'design_product_masters', ['name'], unique=False)
    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_rfc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_profit_margin', sa.Float(), nullable=False),
    sa.Column('cost_tolerance_percent', sa.Float(), nullable=False),
    sa.Column('quote_validity_days', sa.Integer(), nullable=False),
    sa.Column('default_edgebanding_factor', sa.Float(), nullable=False),
    sa.Column('annual_sales_target', sa.Float(), nullable=False),
    sa.Column('last_year_sales', sa.Float(), nullable=False),
    sa.Column('default_tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_receptions',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('reception_date', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_receptions_invoice_number'), 'inventory_receptions', ['invoice_number'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('production_route', sa.Enum('MATERIAL', 'PROCESO', 'CONSUMIBLE', 'SERVICIO', name='productionroute'), nullable=False),
    sa.Column('purchase_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('current_cost', sa.Float(), nullable=False),
    sa.Column('physical_stock', sa.Float(), nullable=False),
    sa.Column('committed_stock', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('associated_element_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_sku'), 'materials', ['sku'], unique=True)
    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uuid_sat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoices_invoice_number'), 'purchase_invoices', ['invoice_number'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'SOLD', 'CLIENT_REJECTED', 'CHANGE_REQUESTED', 'IN_PRODUCTION', 'COMPLETED', 'CANCELLED', name='salesorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('applied_margin_percent', sa.Float(), nullable=False),
    sa.Column('applied_tolerance_percent', sa.Float(), nullable=False),
    sa.Column('applied_commission_percent', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_invoice_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_warranty', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients_v2.id'], ),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['design_product_masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_transactions',
    sa.Column('reception_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['reception_id'], ['inventory_receptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_version_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal_price', sa.Float(), nullable=False),
    sa.Column('cost_snapshot', sa.JSON(), nullable=True),
    sa.Column('frozen_unit_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('TRANSFERENCIA', 'EFECTIVO', 'CHEQUE', 'TARJETA', 'OTRO', name='paymentmethod'), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_version_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['design_product_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_version_components_material_id'), 'design_version_components', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_version_components_material_id'), table_name='design_version_components')
    op.drop_table('design_version_components')
    op.drop_table('supplier_payments')
    op.drop_table('sales_order_items')
    op.drop_table('inventory_transactions')
    op.drop_table('design_product_versions')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_purchase_invoices_invoice_number'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_materials_sku'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_inventory_receptions_invoice_number'), table_name='inventory_receptions')
    op.drop_table('inventory_receptions')
    op.drop_table('global_config')
    op.drop_index(op.f('ix_design_product_masters_name'), table_name='design_product_masters')
    op.drop_table('design_product_masters')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tax_rates')
    op.drop_index(op.f('ix_providers_business_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_clients_v2_full_name'), table_name='clients_v2')
    op.drop_table('clients_v2')
    # ### end Alembic commands ###
