"""Inyeccion Analitica y WMS FINAL

Revision ID: 48250b0dd5d6
Revises: 527a4a8d2805
Create Date: 2026-04-04 19:35:29.416614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48250b0dd5d6'
down_revision: Union[str, Sequence[str], None] = '527a4a8d2805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_purchase_order_items')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.alter_column('quantity_received',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_column('requisition_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.alter_column('invoice_folio_reported',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('invoice_total_reported',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('authorized_by',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('qc_rejections_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_stage_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signed_received_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('administration_invoice_folio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_breakdown_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_installation_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_manufacturing_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('requires_director_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approved_by_director', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('director_approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_column('director_approved_at')
        batch_op.drop_column('is_approved_by_director')
        batch_op.drop_column('requires_director_approval')
        batch_op.drop_column('estimated_manufacturing_cost')
        batch_op.drop_column('estimated_installation_cost')
        batch_op.drop_column('exchange_rate')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_column('category_breakdown_snapshot')

    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.drop_column('administration_invoice_folio')
        batch_op.drop_column('signed_received_at')
        batch_op.drop_column('current_stage_deadline')
        batch_op.drop_column('delivery_deadline')
        batch_op.drop_column('qc_rejections_count')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('authorized_by',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('invoice_total_reported',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('invoice_folio_reported',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('exchange_rate')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requisition_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('quantity_received',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))

    op.create_table('_alembic_tmp_purchase_order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), nullable=False),
    sa.Column('material_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity_ordered', sa.FLOAT(), nullable=False),
    sa.Column('expected_unit_cost', sa.FLOAT(), nullable=False),
    sa.Column('custom_description', sa.VARCHAR(), nullable=True),
    sa.Column('quantity_received', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
