"""add_stone_pieces_to_instances

Revision ID: 50c8908e796b
Revises: d11cf73b0450
Create Date: 2026-04-17 18:44:36.210113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c8908e796b'
down_revision: Union[str, Sequence[str], None] = 'd11cf73b0450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stone_pieces', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.drop_column('stone_pieces')

    # ### end Alembic commands ###
