"""allow_custom_purchases

Revision ID: 527a4a8d2805
Revises: 79df9bfd2fcc
Create Date: 2026-03-24 11:13:56.088070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '527a4a8d2805'
down_revision: Union[str, Sequence[str], None] = '79df9bfd2fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('custom_description')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.alter_column('material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('custom_description')

    # ### end Alembic commands ###
