"""add_petty_cash_tables

Revision ID: 686bdc1e0774
Revises: ff3605386efb
Create Date: 2026-04-25 14:52:25.580026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '686bdc1e0774'
down_revision: Union[str, Sequence[str], None] = 'ff3605386efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_product_masters', schema=None) as batch_op:
        batch_op.drop_column('blueprint_path')

    with op.batch_alter_table('design_product_versions', schema=None) as batch_op:
        batch_op.alter_column('blueprint_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_product_versions', schema=None) as batch_op:
        batch_op.alter_column('blueprint_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('design_product_masters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blueprint_path', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
