"""add_min_max_stock

Revision ID: 79df9bfd2fcc
Revises: e59059eb8863
Create Date: 2026-03-24 10:30:06.966887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79df9bfd2fcc'
down_revision: Union[str, Sequence[str], None] = 'e59059eb8863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        # LE AGREGAMOS server_default='0.0' A AMBAS COLUMNAS
        batch_op.add_column(sa.Column('min_stock', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('max_stock', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('max_stock')
        batch_op.drop_column('min_stock')

    # ### end Alembic commands ###
