"""initial_clean_english

Revision ID: 8391f4b4c2f0
Revises: 
Create Date: 2026-04-16 13:28:28.625294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8391f4b4c2f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_folio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_name'), ['name'], unique=False)

    op.create_table('clients_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfc_tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact2_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact2_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact2_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact2_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact3_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact3_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact3_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact3_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact4_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact4_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact4_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact4_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_v2_full_name'), ['full_name'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)

    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rfc_tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_cellphone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_business_name'), ['business_name'], unique=False)

    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('DIRECTOR', 'GERENCIA', 'ADMIN', 'SALES', 'DESIGN', 'WAREHOUSE', 'PRODUCTION', 'LOGISTICS', name='userrole'), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('monthly_sales_target', sa.Float(), nullable=False),
    sa.Column('monthly_quota', sa.Float(), nullable=True),
    sa.Column('global_commission_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('IN', 'OUT', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('related_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_product_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('blueprint_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_product_masters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_product_masters_name'), ['name'], unique=False)

    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_rfc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_profit_margin', sa.Float(), nullable=False),
    sa.Column('cost_tolerance_percent', sa.Float(), nullable=False),
    sa.Column('quote_validity_days', sa.Integer(), nullable=False),
    sa.Column('default_edgebanding_factor', sa.Float(), nullable=False),
    sa.Column('annual_sales_target', sa.Float(), nullable=False),
    sa.Column('last_year_sales', sa.Float(), nullable=False),
    sa.Column('target_payroll_per_board', sa.Float(), nullable=False),
    sa.Column('target_overhead_per_board', sa.Float(), nullable=False),
    sa.Column('default_leader_daily_rate', sa.Float(), nullable=False),
    sa.Column('default_helper_daily_rate', sa.Float(), nullable=False),
    sa.Column('default_tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('leader_user_id', sa.Integer(), nullable=False),
    sa.Column('helper_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_signature_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence_photos_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_installation_cost', sa.Float(), nullable=True),
    sa.Column('warranty_end_date', sa.DateTime(), nullable=True),
    sa.Column('installer_pay_amount', sa.Float(), nullable=True),
    sa.Column('is_pay_settled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['helper_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installation_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_assignments_instance_id'), ['instance_id'], unique=False)

    op.create_table('inventory_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('authorized_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('actual_dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warehouse_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_dispatches_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_dispatches_production_batch_id'), ['production_batch_id'], unique=False)

    op.create_table('inventory_receptions',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('reception_date', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_receptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_receptions_invoice_number'), ['invoice_number'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('production_route', sa.Enum('MATERIAL', 'PROCESO', 'CONSUMIBLE', 'SERVICIO', name='productionroute'), nullable=False),
    sa.Column('purchase_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('current_cost', sa.Float(), nullable=False),
    sa.Column('physical_stock', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.Column('max_stock', sa.Float(), nullable=False),
    sa.Column('committed_stock', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('associated_element_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_sku'), ['sku'], unique=True)

    op.create_table('product_stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_stock_movements_product_id'), ['product_id'], unique=False)

    op.create_table('production_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'DRAFT', 'ON_HOLD', 'IN_PRODUCTION', 'PACKING', 'READY_TO_INSTALL', 'FINISHED', name='productionbatchstatus'), nullable=False),
    sa.Column('estimated_merma_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_start_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_date', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_merma_percent', sa.Float(), nullable=True),
    sa.Column('actual_payroll_cost', sa.Float(), nullable=True),
    sa.Column('actual_overhead_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_batches_folio'), ['folio'], unique=True)

    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uuid_sat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoices_invoice_number'), ['invoice_number'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('folio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_folio_reported', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_total_reported', sa.Float(), nullable=True),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_advance', sa.Boolean(), nullable=False),
    sa.Column('total_estimated_amount', sa.Float(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('authorized_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_folio'), ['folio'], unique=False)

    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'WAITING_ADVANCE', 'SOLD', 'CLIENT_REJECTED', 'CHANGE_REQUESTED', 'IN_PRODUCTION', 'FINISHED', 'COMPLETED', 'CANCELLED', name='salesorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('applied_margin_percent', sa.Float(), nullable=False),
    sa.Column('applied_tolerance_percent', sa.Float(), nullable=False),
    sa.Column('applied_commission_percent', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('advance_percent', sa.Float(), nullable=False),
    sa.Column('has_advance_invoice', sa.Boolean(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('estimated_installation_cost', sa.Float(), nullable=True),
    sa.Column('estimated_manufacturing_cost', sa.Float(), nullable=True),
    sa.Column('requires_director_approval', sa.Boolean(), nullable=True),
    sa.Column('is_approved_by_director', sa.Boolean(), nullable=True),
    sa.Column('director_approved_at', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_invoice_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_warranty', sa.Boolean(), nullable=False),
    sa.Column('client_po_folio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_po_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_v2.id'], ),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_client_po_folio'), ['client_po_folio'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_project_name'), ['project_name'], unique=False)

    op.create_table('weekly_fixed_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_reference_date', sa.Date(), nullable=False),
    sa.Column('admin_payroll', sa.Float(), nullable=False),
    sa.Column('design_sales_payroll', sa.Float(), nullable=False),
    sa.Column('production_plant_payroll', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_fixed_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_fixed_costs_week_reference_date'), ['week_reference_date'], unique=False)

    op.create_table('customer_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('ADVANCE', 'PROGRESS', 'SETTLEMENT', name='paymenttype'), nullable=False),
    sa.Column('invoice_folio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='cxcstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amortized_advance', sa.Float(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.Enum('TRANSFER', 'CASH', 'CHECK', 'CREDIT_CARD', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('treasury_transaction_id', sa.Integer(), nullable=True),
    sa.Column('commission_paid', sa.Boolean(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['treasury_transaction_id'], ['bank_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treasury_transaction_id')
    )
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_payments_invoice_folio'), ['invoice_folio'], unique=False)

    op.create_table('design_product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('installation_days', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['design_product_masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_audit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Float(), nullable=False),
    sa.Column('counted_quantity', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['inventory_audits.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_dispatch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.Column('picked_quantity', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['inventory_dispatches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_transactions',
    sa.Column('reception_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('operator_badge', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['reception_id'], ['inventory_receptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_project_id'), ['project_id'], unique=False)

    op.create_table('payroll_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('LEADER', 'HELPER', name='payrollpaymenttype'), nullable=False),
    sa.Column('days_worked', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_SIGNATURE', 'READY_TO_PAY', 'PAID', 'DEFERRED', name='payrollstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['installation_assignment_id'], ['installation_assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_payments_installation_assignment_id'), ['installation_assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_payments_user_id'), ['user_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('custom_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity_ordered', sa.Float(), nullable=False),
    sa.Column('expected_unit_cost', sa.Float(), nullable=False),
    sa.Column('quantity_received', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('custom_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_quantity', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin_version_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal_price', sa.Float(), nullable=False),
    sa.Column('cost_snapshot', sa.JSON(), nullable=True),
    sa.Column('frozen_unit_cost', sa.Float(), nullable=False),
    sa.Column('category_breakdown_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('TRANSFERENCIA', 'EFECTIVO', 'CHEQUE', 'TARJETA', 'OTRO', name='paymentmethod'), nullable=False),
    sa.Column('suggested_account_id', sa.Integer(), nullable=True),
    sa.Column('approved_account_id', sa.Integer(), nullable=True),
    sa.Column('treasury_transaction_id', sa.Integer(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['suggested_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['treasury_transaction_id'], ['bank_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treasury_transaction_id')
    )
    op.create_table('design_version_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['design_product_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_version_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_version_components_material_id'), ['material_id'], unique=False)

    op.create_table('sales_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_payment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commission_type', sa.Enum('SELLER', 'DIRECTOR_GLOBAL', name='commissiontype'), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payroll_deferred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_payment_id'], ['customer_payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_commissions_customer_payment_id'), ['customer_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_commissions_user_id'), ['user_id'], unique=False)

    op.create_table('sales_order_item_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_item_id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('production_status', sa.Enum('PENDING', 'IN_PRODUCTION', 'READY', 'CARGADO', 'INSTALLED', 'CLOSED', 'WARRANTY', name='instancestatus'), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('declared_bundles', sa.Integer(), nullable=True),
    sa.Column('customer_payment_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('qc_rejections_count', sa.Integer(), nullable=True),
    sa.Column('delivery_deadline', sa.DateTime(), nullable=True),
    sa.Column('current_stage_deadline', sa.DateTime(), nullable=True),
    sa.Column('signed_received_at', sa.DateTime(), nullable=True),
    sa.Column('administration_invoice_folio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_prod_mdf', sa.DateTime(), nullable=True),
    sa.Column('scheduled_prod_stone', sa.DateTime(), nullable=True),
    sa.Column('scheduled_inst_mdf', sa.DateTime(), nullable=True),
    sa.Column('scheduled_inst_stone', sa.DateTime(), nullable=True),
    sa.Column('warranty_started_at', sa.DateTime(), nullable=True),
    sa.Column('is_warranty_reopened', sa.Boolean(), nullable=False),
    sa.Column('warranty_reopened_at', sa.DateTime(), nullable=True),
    sa.Column('original_signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_payment_id'], ['customer_payments.id'], ),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['sales_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_item_instances_custom_name'), ['custom_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_item_instances_qr_code'), ['qr_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_item_instances_qr_code'))
        batch_op.drop_index(batch_op.f('ix_sales_order_item_instances_custom_name'))

    op.drop_table('sales_order_item_instances')
    with op.batch_alter_table('sales_commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_commissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_commissions_customer_payment_id'))

    op.drop_table('sales_commissions')
    with op.batch_alter_table('design_version_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_version_components_material_id'))

    op.drop_table('design_version_components')
    op.drop_table('supplier_payments')
    op.drop_table('sales_order_items')
    op.drop_table('purchase_requisitions')
    op.drop_table('purchase_order_items')
    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_payments_installation_assignment_id'))

    op.drop_table('payroll_payments')
    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_project_id'))

    op.drop_table('inventory_transactions')
    op.drop_table('inventory_reservations')
    op.drop_table('inventory_dispatch_items')
    op.drop_table('inventory_audit_items')
    op.drop_table('design_product_versions')
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_payments_invoice_folio'))

    op.drop_table('customer_payments')
    with op.batch_alter_table('weekly_fixed_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_fixed_costs_week_reference_date'))

    op.drop_table('weekly_fixed_costs')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_project_name'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_client_po_folio'))

    op.drop_table('sales_orders')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_folio'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_invoice_number'))

    op.drop_table('purchase_invoices')
    with op.batch_alter_table('production_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_batches_folio'))

    op.drop_table('production_batches')
    with op.batch_alter_table('product_stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_stock_movements_product_id'))

    op.drop_table('product_stock_movements')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_sku'))

    op.drop_table('materials')
    with op.batch_alter_table('inventory_receptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_receptions_invoice_number'))

    op.drop_table('inventory_receptions')
    with op.batch_alter_table('inventory_dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_dispatches_production_batch_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_dispatches_instance_id'))

    op.drop_table('inventory_dispatches')
    op.drop_table('inventory_audits')
    with op.batch_alter_table('installation_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_assignments_instance_id'))

    op.drop_table('installation_assignments')
    op.drop_table('global_config')
    with op.batch_alter_table('design_product_masters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_product_masters_name'))

    op.drop_table('design_product_masters')
    op.drop_table('bank_transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tax_rates')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_business_name'))

    op.drop_table('providers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_name'))

    op.drop_table('products')
    with op.batch_alter_table('clients_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_v2_full_name'))

    op.drop_table('clients_v2')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_name'))

    op.drop_table('bank_accounts')
    op.drop_table('accounts_payable')
    # ### end Alembic commands ###
