"""upgrade_produccion_v3_5

Revision ID: 8f8d4fe053d6
Revises: 00e2fa5ba41f
Create Date: 2026-03-02 18:41:20.365944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8d4fe053d6'
down_revision: Union[str, Sequence[str], None] = '00e2fa5ba41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('production_status', sa.Enum('PENDING', 'IN_PRODUCTION', 'READY', 'CARGADO', 'INSTALLED', 'CLOSED', name='instancestatus'), nullable=False))
        batch_op.add_column(sa.Column('production_batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_sales_order_item_instances_custom_name'), ['custom_name'], unique=False)
        batch_op.drop_column('identifier_name')
        batch_op.drop_column('status')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.alter_column('sales_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_project_name'), ['project_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_project_name'))

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.alter_column('sales_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('PENDING', 'IN_PRODUCTION', 'READY', 'CARGADO', 'INSTALLED', 'CLOSED', name='instancestatus'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('identifier_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_sales_order_item_instances_custom_name'))
        batch_op.drop_column('is_cancelled')
        batch_op.drop_column('production_batch_id')
        batch_op.drop_column('production_status')
        batch_op.drop_column('custom_name')

    # ### end Alembic commands ###
