"""diagnostico_v3

Revision ID: be57c28b71f2
Revises: 
Create Date: 2026-01-03 09:27:15.499660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be57c28b71f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfc_tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_full_name'), 'clients', ['full_name'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rfc_tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_business_name'), 'providers', ['business_name'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_rfc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_profit_margin', sa.Float(), nullable=False),
    sa.Column('cost_tolerance_percent', sa.Float(), nullable=False),
    sa.Column('quote_validity_days', sa.Integer(), nullable=False),
    sa.Column('default_edgebanding_factor', sa.Float(), nullable=False),
    sa.Column('default_tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('production_route', sa.Enum('MATERIAL', 'PROCESO', 'CONSUMIBLE', 'SERVICIO', name='productionroute'), nullable=False),
    sa.Column('purchase_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('current_cost', sa.Float(), nullable=False),
    sa.Column('physical_stock', sa.Float(), nullable=False),
    sa.Column('committed_stock', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('associated_element_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_sku'), 'materials', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_sku'), table_name='materials')
    op.drop_table('materials')
    op.drop_table('global_config')
    op.drop_table('tax_rates')
    op.drop_index(op.f('ix_providers_business_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_clients_full_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
