"""add_mdf_hardware_bundles_to_instances

Revision ID: d11cf73b0450
Revises: e21a30bf5441
Create Date: 2026-04-17 17:09:48.691426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11cf73b0450'
down_revision: Union[str, Sequence[str], None] = 'e21a30bf5441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mdf_bundles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hardware_bundles', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.drop_column('hardware_bundles')
        batch_op.drop_column('mdf_bundles')

    # ### end Alembic commands ###
