"""Refactor CustomerPayment a CXC

Revision ID: dba1d785ff5e
Revises: 6cb2a2b23936
Create Date: 2026-03-19 13:27:43.981932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dba1d785ff5e'
down_revision: Union[str, Sequence[str], None] = '6cb2a2b23936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        # Agregamos server_default para evitar errores si la tabla ya tiene datos
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='cxcstatus'), server_default='PENDING', nullable=False))
        batch_op.add_column(sa.Column('invoice_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('treasury_transaction_id', sa.Integer(), nullable=True))
        batch_op.alter_column('payment_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        
        # AQUÍ ESTÁ LA MAGIA: Nombres explícitos para SQLite
        batch_op.create_unique_constraint('uq_customer_payments_treasury', ['treasury_transaction_id'])
        batch_op.create_foreign_key('fk_customer_payments_treasury', 'bank_transactions', ['treasury_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        # AQUÍ TAMBIÉN: Nombres explícitos para poder borrarlos si hacemos rollback
        batch_op.drop_constraint('fk_customer_payments_treasury', type_='foreignkey')
        batch_op.drop_constraint('uq_customer_payments_treasury', type_='unique')
        
        batch_op.alter_column('payment_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('treasury_transaction_id')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###