"""add_evidence_photos_to_instance

Revision ID: f439b0d80c2b
Revises: 7c73a22582fa
Create Date: 2026-04-17 11:01:59.230112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f439b0d80c2b'
down_revision: Union[str, Sequence[str], None] = '7c73a22582fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_photos_urls', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.drop_column('evidence_photos_urls')

    # ### end Alembic commands ###
