"""add_component_flags_and_stone_batch

Revision ID: ff3605386efb
Revises: 50c8908e796b
Create Date: 2026-04-17 19:36:31.494786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff3605386efb'
down_revision: Union[str, Sequence[str], None] = '50c8908e796b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_product_versions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'has_mdf_components',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'has_stone_components',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stone_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_sales_order_item_instances_stone_batch_id',
            'production_batches',
            ['stone_batch_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_item_instances', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_sales_order_item_instances_stone_batch_id',
            type_='foreignkey',
        )
        batch_op.drop_column('stone_batch_id')

    with op.batch_alter_table('design_product_versions', schema=None) as batch_op:
        batch_op.drop_column('has_stone_components')
        batch_op.drop_column('has_mdf_components')

    # ### end Alembic commands ###
